# Daily break limit is now actually counts when the server is online. Once the server restarted it will be reset. I'll create a better solution for this.
# Set 0 to disable
daily-broke-limit: 5

# Checks new version and prints to the console and to OP's when they join.
# Set false to disable.
update-check: true

# It depends on the language of the player's client. Currently only English and Hungarian languages supported.
# If you want to add your language, just create a [PR](https://github.com/poma123/PickupSpawners/pulls)!
# Set false to disable
auto-locale: true

# If auto-locale is disabled, the plugin uses this language.
locale: 'en_US'

# You can set spawner breaker items ingame, check the wiki page for more information.
item: {}

spawner-change:
  disabledTypes: []
#    - 'VILLAGER'
