# Daily break limit now counts daily.
# The default's permission is pickupspawners.breaklimit.default, and is true for everyone.
# You can add here more limits. The 'vip' named limit's permission is pickupspawners.breaklimit.vip
# Set 0 to disable
break-limits:
  default: 0
#  vip: 10

# Checks new version and prints to the console and to OP's when they join.
# Set false to disable.
update-check: true

# It depends on the language of the player's client. Currently, only English and Hungarian languages are supported.
# If you want to add your language, just create a [PR](https://github.com/poma123/PickupSpawners/pulls)!
# Set false to disable
auto-locale: true

# If auto-locale is disabled, the plugin uses this language.
locale: 'en_US'

# You can set spawner breaker items ingame, check the wiki page for more information.
item: {}

spawner-change:
  disabledTypes: []
#    - 'VILLAGER'
