name: PickupSpawners
version: 2.9.0
main: me.poma123.spawners.PickupSpawners
api-version: 1.13
softdepend: [Vault]
permissions:
  spawnerlimit.bypass:
    default: op
  pickupspawners.give:
    default: op
  pickupspawners.additem:
    default: op
  pickupspawners.removeitem:
    default: op
  pickupspawners.itemlist:
    default: op
  pickupspawners.signshop.use:
    default: true
  pickupspawners.signshop.create:
    default: op
  pickupspawners.gui:
    default: op
  pickupspawners.change:
    default: op
  pspawners.updateitem:
    default: op
  pspawners.setitempermission:
    default: op
  pspawners.removeitempermission:
    default: op
commands:
  pickupspawners:
    usage: /<command>
    description: PickupSpawners main command
    aliases: [spawners, pspawners, pickups]