author: poma123
main: me.poma123.spawners.Command
name: PickupSpawners
api-version: 1.13
version: 2.5.1
permissions:
    spawnerlimit.bypass:
        default: op
    pickupspawners.give:
        default: op    
commands:
    pickupspawners:
        usage: /<command>
        aliases: [spawners, pspawners, pickups]